name: "New Idea"
description: Request to implement new capability (will be prioritised
  at planning)
labels: [new-idea]
body: 
- type: textarea
  id: motivation
  attributes:
    label: Motivation
    description: Describe benefits of implementing this platform capability
    placeholder: Describe benefits of implementing this platform capability
  validations:
    required: true
- type: textarea
  id: scope
  attributes:
    label: Scope
    description: Define scope of the new capability
    placeholder: Define scope of the new capability
  validations:
    required: false
- type: textarea
  id: requirements
  attributes:
    label: Requirements
    description: List down success criteria to implement the capability
    placeholder: List down success criteria to implement the capability
  validations:
    required: true
- type: textarea
  id: assumptions
  attributes:
    label: Assumptions (Optional)
    description: Describe any assumptions made for the delivery of the capability
    placeholder: Describe any assumptions made for the delivery of the capability
  validations:
    required: false
- type: textarea
  id: dependency
  attributes:
    label: Dependencies (Optional)
    description: List of deliverables this issue depends on
    placeholder: List of deliverables this issue depends on
  validations:
    required: false
- type: checkboxes
  id: dod
  attributes:
    label: Definition of Done
    options:
    - label: Scope and Requirements agreed
      required: true
    - label: Design Defuzz on
      required: true
- type: checkboxes
  id: designdefuzz
  attributes:
    label: Design Defuzz on
    options:
    - label: I have searched the existing issues
      required: true
- type: checkboxes
  id: hld
  attributes:
    label: High Level Design diagrams & Documentation Created / Updated
    options:
    - label: I have searched the existing issues
      required: true     
- type: checkboxes
  id: adr
  attributes:
    label: Architecture decision records created
    options:
    - label: I have searched the existing issues
      required: true      
- type: checkboxes
  id: deploysuccess
  attributes:
    label: Deployed to all relevant environments successfully
    options:
    - label: I have searched the existing issues
      required: true    
- type: checkboxes
  id: runbooksupdated
  attributes:
    label: Runbooksupdated
    options:
    - label: I have searched the existing issues
      required: true
- type: checkboxes
  id: logmonitoralerts
  attributes:
    label: Logging, Monitoring & Alerts set up / updated
    options:
    - label: I have searched the existing issues
      required: true     
- type: checkboxes
  id: demo
  attributes:
    label: Demoed in showcase
    options:
    - label: I have searched the existing issues
      required: true
