name: "New Idea"
description: Request to implement new capability (will be prioritised
  at planning)
labels: [new-idea]
body: |-
  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Describe benefits of implementing this platform capability
      placeholder: Describe benefits of implementing this platform capability
    validations:
      required: true
  - type: textarea
    id: scope
    attributes:
      label: Scope
      description: Define scope of the new capability
      placeholder: Define scope of the new capability
    validations:
      required: false
  - type: textarea
    id: requirements
    attributes:
      label: Requirements
      description: List down success criteria to implement the capability
      placeholder: List down success criteria to implement the capability
    validations:
      required: true
  - type: textarea
    id: assumptions
    attributes:
      label: Assumptions (Optional)
      description: Describe any assumptions made for the delivery of the capability
      placeholder: Describe any assumptions made for the delivery of the capability
    validations:
      required: false
  - type: textarea
    id: dependency
    attributes:
      label: Dependencies (Optional)
      description: List of deliverables this issue depends on
      placeholder: List of deliverables this issue depends on
    validations:
      required: false
  - type:markdown
     id: definitionOfDone
     attributes:
       value:Definition of Done
  - type: checkboxes
    id: scopedefined
    attributes:
      label: Scope and Requirements agreed
      required: true
  - type: checkboxes
    id: designdefuzz
    attributes:
      label: Design Defuzz on
      required: true
  - type: checkboxes
    id: hld
    attributes:
      label: High Level Design diagrams & Documentation Created / Updated
      required: true     
  - type: checkboxes
    id: adr
    attributes:
      label: Architecture decision records created
      required: true      
  - type: checkboxes
    id: deploysuccess
    attributes:
      label: Deployed to all relevant environments successfully
      required: true    
  - type: checkboxes
    id: runbooks updated
    attributes:
      label: Runbooks updated
      required: true
  - type: checkboxes
    id: log_monitor_alerts
    attributes:
     label: Logging, Monitoring & Alerts set up / updated
     required: true     
  - type: checkboxes
    id: demo
    attributes:
     label: Demoed in showcase
     required: true
