name: "New Idea"
description: Request to implement new capability (will be prioritised
  at planning)
labels: [new-idea]
body: 
- type: textarea
  id: motivation
  attributes:
    label: Motivation
    placeholder: Describe benefits of implementing this platform capability
  validations:
    required: true
- type: textarea
  id: scope
  attributes:
    label: Scope
    description: Scope of the new capability
    placeholder: Define scope of the new capability
  validations:
    required: false
- type: textarea
  id: requirements
  attributes:
    label: Requirements
    description: Success criteria to implement the capability
    placeholder: List down success criteria to implement the capability
  validations:
    required: true
- type: textarea
  id: assumptions
  attributes:
    label: Assumptions (Optional)
    description: Assumptions made for the delivery of the capability
    placeholder: Describe any assumptions made for the delivery of the capability
  validations:
    required: false
- type: textarea
  id: dependency
  attributes:
    label: Dependencies (Optional)
    description: List of deliverables this issue depends on
    placeholder: List of deliverables this issue depends on
  validations:
    required: false
- type: checkboxes
  id: dod
  attributes:
    label: Definition of Done
    options:
    - label: Scope and Requirements agreed
      required: true
    - label: Design Defuzz on
      required: true
    - label: High Level Design diagrams & Documentation Created / Updated
    - label: Architecture decision records created
    - label: Deployed to all relevant environments successfully
    - label: Runbooks Updated
    - label: Logging, Monitoring & Alerts set up / updated
    - label: Demoed in showcase
- type: textarea
  id: notes
  attributes:
    label: Notes & Questions
    description: Any Notes and Questions
    placeholder: Any Notes and open questions related to the issue goes here
  validations:
    required: false
